"""Make order_number not null

Revision ID: 73a606b4d11c
Revises: 2c8282184f9c
Create Date: 2024-09-28 06:38:09.953548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73a606b4d11c'
down_revision = '2c8282184f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('repair_logs')
    # op.drop_table('users')
    with op.batch_alter_table('repairs', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repairs', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('repair_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('repair_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('log_entry', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], name='repair_logs_repair_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='repair_logs_pkey')
    )
    # ### end Alembic commands ###
